name: "\U0001F41E Bug Report"
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug"]
assignees:
  - MeetinaXD
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: framework
    attributes:
      label: Framework
      description: Please choose the framework of the impact of this issue.
      multiple: false
      options:
        - 'React'
        - 'Vue'
        - 'Svelte'
        - 'Other Framework'
    validations:
      required: true
