blank_issues_enabled: false
contact_links:
  - name: Official Documentation
    url: https://alova.js.org
    about: Before submitting a bug, you can first look for a solution through the official documentation

  - name: Discord Chat
    url: https://discord.gg/S47QGJgkVb
    about: Ask questions and discuss with other users in real time.

  - name: QQ频道
    url: https://pd.qq.com/s/1cdjx0nnw
    about: 在 QQ 频道中和我们交流.

  - name: Questions & Discussions
    url: https://github.com/alovajs/alova/discussions
    about: Use GitHub discussions for your questions and discussions.